# PR Verification Workflow — analyze and verify pull request readiness
#
# Usage:
#   routa workflow run resources/flows/pr-verify.yaml --trigger-payload '{"pr_number": 42, "repo": "owner/repo"}'
#
# This workflow is triggered by GitHub webhooks (pull_request.opened, pull_request.synchronize)
# or manually to verify PR quality before merge.

name: "PR Verification Flow"
description: "Multi-phase PR verification: analyze requirements, check reviews, verify build, run E2E"
version: "1.0"

trigger:
  type: webhook
  source: github
  event: pull_request

variables:
  model: "${ANTHROPIC_MODEL:-claude-sonnet-4-20250514}"

steps:
  # Phase 1: Analyze PR body and extract requirements
  - name: "Analyze Requirements"
    specialist: "pr-analyzer"
    adapter: "claude-code-sdk"
    config:
      model: "${model}"
    input: |
      Analyze this Pull Request and extract structured information:

      ${trigger.payload}

      Tasks:
      1. Parse the PR body to extract:
         - Linked Issues (e.g., "Fixes #123", "Closes #456")
         - Acceptance Criteria / Requirements
         - Breaking Changes section
         - Screenshots or visual evidence
         - Testing instructions

      2. Identify verification requirements:
         - Required test scenarios
         - Manual verification steps
         - Expected behavior changes

      3. Output a structured summary in JSON format with:
         - linked_issues: string[]
         - acceptance_criteria: string[]
         - breaking_changes: string[]
         - has_screenshots: boolean
         - test_scenarios: string[]

    output_key: "requirements_analysis"

  # Phase 2: Analyze review comments
  - name: "Analyze Reviews"
    specialist: "pr-analyzer"
    adapter: "claude-code-sdk"
    config:
      model: "${model}"
    input: |
      Based on the PR requirements analysis:

      ${steps.Analyze Requirements.output}

      Now analyze all review comments on this PR:

      ${trigger.payload}

      Tasks:
      1. Categorize each comment as:
         - RESOLVED: Already addressed
         - PENDING: Needs attention but not blocking
         - BLOCKING: Must be fixed before merge

      2. Identify:
         - Code quality concerns
         - Security issues raised
         - Performance concerns
         - Documentation gaps

      3. Provide a summary of review status and any blocking issues.

    output_key: "review_analysis"

  # Phase 3: Check build and CI status
  - name: "Verify Build Status"
    specialist: "pr-analyzer"
    adapter: "claude-code-sdk"
    config:
      model: "${model}"
    input: |
      Check the CI/Build status for this PR:

      ${trigger.payload}

      Previous analysis:
      - Requirements: ${steps.Analyze Requirements.output}
      - Reviews: ${steps.Analyze Reviews.output}

      Tasks:
      1. Use GitHub API to check:
         - Build status (passing/failing)
         - Test results
         - Lint check results
         - Type check results

      2. If any checks are failing, analyze the failure logs.

      3. Provide build verification summary:
         - all_checks_passing: boolean
         - failed_checks: string[]
         - failure_analysis: string (if any)

    output_key: "build_status"

  # Phase 4: Generate verification verdict
  - name: "Generate Verdict"
    specialist: "pr-analyzer"
    adapter: "claude-code-sdk"
    config:
      model: "${model}"
    input: |
      Generate a final PR verification verdict based on all analysis:

      ## Requirements Analysis
      ${steps.Analyze Requirements.output}

      ## Review Analysis
      ${steps.Analyze Reviews.output}

      ## Build Status
      ${steps.Verify Build Status.output}

      ## Original PR
      ${trigger.payload}

      Provide a decision matrix:
      | Criteria | Status | Details |
      |----------|--------|---------|
      | Requirements Clear | ✅/❌ | ... |
      | Reviews Addressed | ✅/❌ | ... |
      | Build Passing | ✅/❌ | ... |
      | Ready to Merge | ✅/❌ | ... |

      Recommendation:
      - APPROVE: All criteria met
      - REQUEST_CHANGES: List specific items to fix
      - NEEDS_DISCUSSION: Unclear requirements or design decisions

    output_key: "verdict"

