# SDLC Workflow — End-to-end software development lifecycle
#
# This workflow implements a simplified SDLC pipeline:
# 1. Refine the requirements from the input
# 2. Plan the implementation
# 3. Review the plan
#
# Usage:
#   routa workflow run resources/flows/sdlc.yaml --trigger-payload "Add a login page with OAuth support"
#   routa workflow run resources/flows/sdlc.yaml -v --trigger-payload "Fix the bug in the payment module"

name: "SDLC Flow"
description: "End-to-end software development lifecycle with requirement refinement, planning, and review"
version: "1.0"

trigger:
  type: manual

variables:
  model: "${ANTHROPIC_MODEL:-GLM-4.7}"
  base_url: "${ANTHROPIC_BASE_URL:-https://open.bigmodel.cn/api/anthropic}"

steps:
  - name: "Refine Requirements"
    specialist: "issue-refiner"
    adapter: "claude-code-sdk"
    config:
      model: "${model}"
      base_url: "${base_url}"
    input: |
      Please analyze the following requirement and break it down into actionable tasks:

      ${trigger.payload}
    actions:
      - analyze_requirements
      - generate_acceptance_criteria
      - identify_dependencies
    output_key: "refined_requirements"

  - name: "Plan Implementation"
    specialist: "developer"
    adapter: "claude-code-sdk"
    config:
      model: "${model}"
      base_url: "${base_url}"
    input: |
      Based on the following refined requirements, create a detailed implementation plan:

      ${steps.Refine Requirements.output}

      Please provide:
      1. Technology choices and rationale
      2. Step-by-step implementation plan
      3. Risk assessment
      4. Estimated effort for each step
    output_key: "implementation_plan"

  - name: "Review Plan"
    specialist: "gate"
    adapter: "claude-code-sdk"
    config:
      model: "${model}"
      base_url: "${base_url}"
    input: |
      Review the following implementation plan against the original requirements.

      ## Original Requirement
      ${trigger.payload}

      ## Refined Requirements
      ${steps.Refine Requirements.output}

      ## Implementation Plan
      ${steps.Plan Implementation.output}

      Verify:
      1. Does the plan cover all acceptance criteria?
      2. Are there any gaps or missing requirements?
      3. Is the plan feasible and well-structured?
    output_key: "plan_review"
