# Simple single-step workflow — quick developer task
#
# Usage:
#   routa workflow run resources/flows/simple-dev.yaml --trigger-payload "Add error handling to the API routes"

name: "Simple Developer Task"
description: "Single-step workflow that sends a task to a developer specialist"
version: "1.0"

trigger:
  type: manual

variables:
  model: "${ANTHROPIC_MODEL:-GLM-4.7}"

steps:
  - name: "Execute Task"
    specialist: "developer"
    adapter: "claude-code-sdk"
    config:
      model: "${model}"
    input: |
      ${trigger.payload}
    output_key: "result"
